### ISSUE TITLE
Unable to open save

### ISSUE THREAD

**Issue by tneo** [tobspr-games/shapez.io#1416]
My save game apparently is broken overnight. It consistently throws a checksum error. Is there something I can do to fix my save?

**Comment by EmeraldBlock** [comment]
could you send your savegame and a screenshot of the error? also, do you have any mods?

**Comment by tneo** [comment]
Sure:
Save: [savegame-8ee471d4dafb54323528d3235ddca4e8ec62e6bc.bin.tar.gz](https://github.com/tobspr/shapez.io/files/8652186/savegame-8ee471d4dafb54323528d3235ddca4e8ec62e6bc.bin.tar.gz)
Error: ![Screenshot_20220508_143237](https://user-images.githubusercontent.com/6168186/167422253-11847c8a-f7a0-4733-b9cf-b97109a4dc7d.png)

**Comment by tneo** [comment]
@tobspr @EmeraldBlock 
Is a/ my save salvageable? Hate to loose all the hours put into the game.

**Comment by tneo** [comment]
The game crashed and I noticed that co-insides often with the saving process often. It will turn the screen black and I have to go to Steam and click on stop to stop Shapez.

**Comment by tutacat** [comment]
> I have to go to Steam and click on stop to stop Shapez.

In general, this is best avoided, because after a timeout, it is just killing it like task manager (or End Program from a not responding message). If a game window is still open, it is best to click the X button or Alt-F4, and try to wait some time. During such operation, it may be running on the main thread and take longer, meaning it doesn't send the window signal to receive events and "respond" to the window manger.

**Comment by tneo** [comment]
It turned out I had a faulty memory bank causing crashes.
