### ISSUE TITLE
when making the logo shape

### ISSUE THREAD

**Issue by Twiddler1** [tobspr-games/shapez.io#1526]
When I got to the lvl 20 logo shape the line runs and puts out about 5 or 6 of the shapes and then stops, it seems to be connected with the belt running into the stacker carrying the upper right square, because I can replace one piece of belt just before that stacker only and it will produce about 5 more then stop again until I replace that piece again. Have also tried replacing other belt pieces, those do nothing just that one for the upper right square. The part of the belt that I replace that makes it work again is the belt just under the raw shape just before the stacker, and as screenshot shows it does produce the required shape, it just stops. The second shot is with the piece in question taken out. I also let the line fill so all pieces produced are on screen.
![Screenshot (2)](https://user-images.githubusercontent.com/130432724/231204284-694eff8f-8fc9-4ccf-9f41-1c6e66ccf899.png)
![Screenshot (6)](https://user-images.githubusercontent.com/130432724/231208169-a893e311-0705-4779-9b4e-b8fefef3ba0a.png)

**Comment by EmeraldBlock** [comment]
Your quad cutter is backed up because you use two shapes from the middle quad cutter output for every one shape from the top (and one shape from the bottom), hence the middle lane running dry while the top lane backs up into the quad cutter, preventing it from outputting more shapes.

Closing since this is not an issue with the game; if you'd like help with your design, feel free to join the [discord server](https://discord.com/invite/HN7EVzV).

**Comment by Twiddler1** [comment]
Thank You, don't know why I brainfarted so hard lol. I have a double feed now on both quarter circles.
