### ISSUE TITLE
How does the unassembly work ?

### ISSUE THREAD

**Issue by MyosotisArae** [tobspr-games/shapez.io#1539]
Hello.
I thought the unassembly machine could tell you how to put parts together. But I think I didn't understand : I did what it showed, but the part inside is too big. Is there another tutorial, more detailed, to explain that point ?
![image](https://user-images.githubusercontent.com/10477676/232288112-e9e3d4b0-9cb2-4205-b0c7-3e5e06531284.png)

**Comment by EmeraldBlock** [comment]
See #1536. Stacking will try to put the top shape as low/big as possible, which allows for merging two halves together. "Unstacking" just looks for the top layer, and when you try to restack it, in this case the top layer is "unstable" because the layer below it does not directly hold it up.

In any case, this isn't the place to ask questions; you can ask in the Discord server.
