### ISSUE TITLE
Export map as image in high quality

### ISSUE THREAD

**Issue by 1RandomDev** [tobspr-games/shapez.io#1549]
I don't really care how long it would take and how big the file will get, but it would be great if you could export the map in a really high quality. Would be great if such a feature could be implemented. And for now is there maybe a variable in the code that I can increase for a quick and dirty fix?

**Comment by EmeraldBlock** [comment]
try my mod! <https://emeraldblock.github.io/shapez/mods/screenshots/>
Note that, no matter what, the canvas the screenshot renders on has a hard limit of around 16,384x16,384. 

Otherwise, there is no quick and dirty fix, since all relevant code is in a screenshot function (and there are other issues, see the mod page for a list).

**Comment by 1RandomDev** [comment]
Oh thanks that's much better :D
