### ISSUE TITLE
Mac delete button doesn't work for deleting anymore

### ISSUE THREAD

**Issue by bbugh** [tobspr-games/shapez.io#587]
Not sure when this updated because I haven't played in a while, but when selecting things, the "delete" button on the Mac keyboard no longer deletes the items. I've tried on the latest release version and on the current head 93f9d7ae2300729363319c02b6e1d7795dc9b0d1.

**Comment by LeigerGaming** [comment]
Right-click should work for delete.

Are you playing in the browser?

**Comment by bbugh** [comment]
It is in the browser. The problem seems to be the bindings In the UI are saying "Del" is a key binding for delete but that doesn't work correctly on Mac anymore. Typically the backspace binding works as a delete equivalent.

**Comment by LeigerGaming** [comment]
I've been playing a bit since reading your original comment - and I can confirm that the `Delete` key on a full-size standard US-layout keyboard works fine, but `Backspace` does not delete things.

On a smaller keyboard that does not include a number pad or separated arrow keys (like the one built into a MacBook), the standard `Backspace` key is actually labelled `delete` - and acts like a `Backspace` key located to the right of the `+` or `=` key and above the `|` or `\` key on a standard US keyboard.

I am not sure if it previously deleted items - sounds like it did - but I can confirm that it currently does not. And therefore the only way to delete items on a MacBook without an external keyboard plugged in is to try to right-click on the trackpad.

You might be able to set up three-button simulation in the OS settings as a workaround, which involves holding the `option` key and left-clicking to perform a right-click (and therefore an opt-click should delete items in the game). But that's more of a workaround than a fix.

**Comment by gileswells** [comment]
As a workaround, and what I've had to use since I started playing, on smaller keyboards you can use `fn + delete` to make it work.

**Comment by EmeraldBlock** [comment]
Issue is with Mac keyboard labeling, and the key can be rebound anyway.

#1291 would allow for backspace to be an alias for delete.
