### ISSUE TITLE
[Feature Request] - Extra Color Wires

### ISSUE THREAD

**Issue by EmileAvatar** [tobspr-games/shapez.io#860]
Can we have more color wires eg Red, Cyan, Magenta, Yellow and White. 

This will allow more complex factory where where 2 wires limits.
It will also help organize having colored more colored wires

**Comment by EmeraldBlock** [comment]
I feel that that may be too much - With that many wires, a lot of challenge would go away, but at the same time, nothing interesting results.

**Comment by EmileAvatar** [comment]
What about only having 3 Wires Total: Blue, Green and Red?

**Comment by EmeraldBlock** [comment]
Honestly, I'm not sure. I personally wish the regular wire insulator was added back (plus the ability to swap wire colors using insulators), and I feel that that would suffice for making complex wires machines

**Comment by Hyperion-21** [comment]
As far as I can tell, unless I'm missing something on a grid you only need 3 colors.
![shapez_wiremap](https://user-images.githubusercontent.com/69665635/95788188-e5c9db00-0c8f-11eb-9d77-49e9dc2922af.png)

**Comment by EmeraldBlock** [comment]
I believe you need 4 in some cases

**Comment by Hyperion-21** [comment]
example?

**Comment by EmeraldBlock** [comment]
![image](https://user-images.githubusercontent.com/69981203/95790100-5da20080-0ca4-11eb-8676-21f57cf9a9fb.png)

**Comment by EmileAvatar** [comment]
Another example. of having extra wires can help organize the wires.
![Shapez IO example complex wires](https://user-images.githubusercontent.com/40697228/95896175-2149cf80-0d8c-11eb-8785-0ccfd87c95c5.PNG)

**Comment by EmeraldBlock** [comment]
If the sole purpose of having extra wires is to color-code them, I would recommend vouching for a visual delimiter that can be used to color any tile. (Also oh no, the building layer disappears)

**Comment by EmileAvatar** [comment]
I See a slight issue with it. How will the two or more wires be next two each other? Will they not mix?
If we have a wire just for a signal (0/1), one for Shape, one for Color then it would work as the wires would not mix.
My thinking is of the times when you have a few eg Filters / logic gates in a tight cluster and need 3 or more wires at the time to do the complex logic

**Comment by santa-klaus** [comment]
For me trying to make it work with two wires is actually part of the fun, but of course it doesn't always work as compact, efficiently or neat as when there were more colors. However, then you could also wish for multiple wires in one tile and so on... I personally prefer it with just two colors, even though I understand the wish.

**Comment by jfxg** [comment]
> For me trying to make it work with two wires is actually part of the fun, but of course it doesn't always work as compact, efficiently or neat as when there were more colors.

The challenge of figuring out how to lay out all of the components is absolutely core to this game, of course. However, I think the issue in this case is the balance between the players' *desire* to condense and tidy up their layout and their *ability* to. Only having two colors to choose from presents a pretty big challenge, which can be a lot of fun... but when other other structures allow for, and even encourage, very dense architectures then it drives a pretty strong desire to want to do the same for the wiring. In many cases it is simply not possible to arrange the buildings in a neatly packed arrangement due to the wiring constraints. It's no longer a puzzle at that point, it's just a barrier, which is a problem.

> However, then you could also wish for multiple wires in one tile and so on... I personally prefer it with just two colors, even though I understand the wish.

I think the crucial aspect is the balance between the buildings. Yes you can always ask for more and more capabilities to make things smaller, but thats not the issue here. The issue is the imbalance between the density of structures: Many buildings allowing for very tight layouts, but wires require more space. The conflict is frustrating. So its not just about wanting more and more better things, its about certain types standing-out compared to the rest of the game. Wanting multiple wires on one tile would be awesome... but it doesn't feel like a reasonable ask because it would be very out of place; nothing else in the game allows you to have two of the same thing at the same time. But, running wires feels a lot like running belts, and we already have the ability to very tightly control where belts go and have many distinct belts wound around each other. Not having the capability to do the same with wires feels out of place, an imbalance in the game.

**Comment by santa-klaus** [comment]
Good points @jfxg, these are very compelling arguments!

**Comment by zifnab0** [comment]
It is very frustrating not to be able to make compact strutures just because of wiring. If not adding more colors, maybe the solution could be to avoid automatic connection between adjacent wires and make them manual. In that case, one color would even be sufficient.

**Comment by dengr1065** [comment]
Not planned for the vanilla game, but exists in Wires+ mod.
